LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views as app_views, user_login
from forum_app import views as forum_views
from django.conf import settings
from django.conf.urls.static import static
from . import candy

urlpatterns = [

    path('admin/', admin.site.urls),

    *candy.path('base', app_views.BASE,name='base'),

    *candy.path('404', app_views.PAGE_NOT_FOUND, name='404'),

    *candy.path('', app_views.HOME,name='home'),

    *candy.path('courses', app_views.SINGLE_COURSE,name='single_course'),

    *candy.path('courses/filter-data',app_views.filter_data,name="filter-data"),

    *candy.path('course/<slug:slug>',app_views.COURSE_DETAILS,name='course_details'),

    *candy.path('search',app_views.SEARCH_COURSE,name='search_course'),

    *candy.path('contact', app_views.CONTACT_US,name='contact_us'),

    *candy.path('about', app_views.ABOUT_US,name='about_us'),

    *candy.path('become-an-instructor', app_views.BECOME_AN_INSTRUCTOR,name='become_an_instructor'),

    *candy.path('coming_soon', app_views.COMING_SOON,name='coming_soon'),

    *candy.path('event', app_views.EVENT,name='event'),

    *candy.path('accounts/register', user_login.REGISTER, name='register'),

    *candy.path('accounts/learner-register', user_login.LEARNER_SIGNUP, name='learner_register'),

    *candy.path('accounts/instructor-register', user_login.INSTRUCTOR_SIGNUP, name='instructor_register'),

    path('accounts/', include('django.contrib.auth.urls')),

    *candy.path('password_reset', app_views.PASSWORD_RESET,name='password_reset'),

    *candy.path('doLogin', user_login.DO_LOGIN, name='doLogin'),

    *candy.path('accounts/profile', user_login.PROFILE, name='profile'),
    *candy.path('accounts/password', user_login.PASSWORD, name='password'),

    *candy.path('accounts/profile/update', user_login.PROFILE_UPDATE, name='profile_update'),
    *candy.path('accounts/password/update', user_login.CHANGE_PASSWORD, name='password-update'),

    *candy.path('my-course',app_views.MY_COURSE,name='my-course'),

    path('course/watch-course/<slug:slug>',app_views.WATCH_COURSE,name='watch-course'),

    *candy.path('course/<slug:course_slug>/<slug:quizz_slug>',app_views.QUIZ,name='quiz'),

    path('course/<slug:course_slug>/<slug:quizz_slug>/data', app_views.quiz_data_view, name='quiz-data-view'),

    path('course/<slug:course_slug>/<slug:quizz_slug>/save',
         app_views.save_quiz_view, name='save_quiz_view'),

    path('download_avatar/<int:user_id>/', app_views.download_avatar, name='download_avatar'),

    #INSTRUCTOR
    *candy.path('instructor-dashboard', app_views.INSTRUCTOR_SITE, name='instructor-dashboard'),
    *candy.path('instructor-course', app_views.INSTRUCTOR_COURSE, name='instructor-course'),
    *candy.path('instructor-lesson', app_views.INSTRUCTOR_LESSON, name='instructor-lesson'),
    *candy.path('instructor-video', app_views.INSTRUCTOR_VIDEO, name='instructor-video'),
    *candy.path('instructor-quiz', app_views.INSTRUCTOR_QUIZZ, name='instructor-quiz'),
    *candy.path('instructor-question', app_views.INSTRUCTOR_QUESTION, name='instructor-question'),
    *candy.path('instructor-profile', app_views.INSTRUCTOR_PROFILE, name="instructor-profile"),
    *candy.path('instructor-change-password', app_views.INSTRUCTOR_CHANGE_PASSWORD, name="instructor-change-password"),

    #INSTRUCTOR CREATE
    *candy.path('create_course_form', app_views.InstructorCreateCourse, name="create_course_form"),
    *candy.path('create_lesson_form', app_views.InstructorCreateLesson, name="create_lesson_form"),
    *candy.path('create_quiz_form', app_views.InstructorCreateQuiz, name="create_quiz_form"),
    *candy.path('create_video_form', app_views.InstructorCreateVideo, name="create_video_form"),
    *candy.path('create_question_form', app_views.create_question_with_answers, name="create_question_form"),
    *candy.path('create_answer_form', app_views.InstructorCreateQuestion, name="create_answer_form"),
    *candy.path('video-lecture/details/<slug:slug>/',app_views.InstructorUpdateVideo,name='video_lecture_details'),
    *candy.path('lesson/details/<slug:slug>/',app_views.InstructorUpdateLesson,name='lesson_details'),
    *candy.path('instructor-course/details/<slug:slug>/',app_views.InstructorUpdateCourse ,name='instructor_course_details'),
    *candy.path('quiz/details/<slug:slug>/',app_views.InstructorUpdateQuiz ,name='quiz_details'),
    *candy.path('question/details/<slug:slug>/',app_views.InstructorUpdateQuestion ,name='question_details'),

    #INSTRUCTOR UPDATE
    *candy.path('update_course_form', app_views.InstructorUpdateCourse, name="update_course_form"),
    *candy.path('update_lesson_form', app_views.InstructorUpdateLesson, name="update_lesson_form"),
    *candy.path('update_quiz_form', app_views.InstructorUpdateQuiz, name="update_quiz_form"),
    *candy.path('update_video_form', app_views.InstructorUpdateVideo, name="update_video_form"),

    #INSTRUCTOR SEARCH
    *candy.path('instructor/search/course',app_views.INSTRUCTOR_SEARCH_COURSE,name='instructor_search_course'),
    *candy.path('instructor/search/lesson',app_views.INSTRUCTOR_SEARCH_LESSON,name='instructor_search_lesson'),
    *candy.path('instructor/search/quiz',app_views.INSTRUCTOR_SEARCH_QUIZZ,name='instructor_search_quiz'),
    *candy.path('instructor/search/question',app_views.INSTRUCTOR_SEARCH_QUESTION,name='instructor_search_question'),
    *candy.path('instructor/search/video-lecture',app_views.INSTRUCTOR_SEARCH_VIDEO_LECTURE,name='instructor_search_video_lecture'),

    #INSTRUCTOR UPDATE INFORMATION
    *candy.path('instructor/accounts/profile/update', user_login.INSTRUCTOR_PROFILE_UPDATE, name='instructor_profile_update'),
    *candy.path('instructor/accounts/change-password', user_login.INSTRUCTOR_CHANGE_PASSWORD, name='instructor_change_password'),

    #NOTE
    *candy.path('edit-note',app_views.EDIT_NOTE,name='edit_note'),
    *candy.path('create-note',app_views.CREATE_NOTE,name='create_note'),
    *candy.path('delete-note',app_views.DELETE_NOTE,name='delete_note'),

    # email activate
    path('activate/<uidb64>/<token>', user_login.activate, name='activate'),
    path('instructor/activate/<uidb64>/<token>', user_login.save_draft_instructor_account, name='save_draft_instructor_account'),

    #FORUM
    path('forum', forum_views.forum_home, name="forum_home"),
    path('room/<str:pk>/', forum_views.room, name="room"),
    path('profile/<str:pk>/', forum_views.userProfile, name="user-profile"),
    path('topics/', forum_views.topicsPage, name="topics"),
    path('activity/', forum_views.activityPage, name="activity"),
    path('delete-message/<str:pk>/', forum_views.deleteMessage, name="delete-message"),
    path('create-room/', forum_views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', forum_views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', forum_views.deleteRoom, name="delete-room"),

    #PAYMENT
    path('paypal/', include('paypal.standard.ipn.urls')),
    *candy.path('payment-success/<slug:slug>', app_views.PAYMENT_SUCCESS,name='payment-success'),
    *candy.path('payment-failed/<slug:slug>', app_views.PAYMENT_FAILED,name='payment-failed'),
    *candy.path('checkout/<slug:slug>',app_views.CHECKOUT,name='checkout'),
    *candy.path('checkout_free_course/<slug:slug>',app_views.CHECKOUT_FREE_COURSE,name='checkout_free_course'),
    # *candy.path('create_payment',app_views.CREATE_PAYMENT,name='create_payment'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

LMS/app/models.py
import django.db.models.deletion
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
import random

class Categories(models.Model):
    icon = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_all_category(self):
        return Categories.objects.all().order_by('id')

class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    name = models.CharField(max_length=100, null=True)
    about_author = models.TextField()

    def __str__(self):
        return self.name

class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language

class Course(models.Model):
    STATUS = (
        ('PUBLISH','PUBLISH'),
        ('DRAFT', 'DRAFT'),
    )
    COURSE_TYPE = (
        ('FREE', 'FREE'),
        ('PAID', 'PAID'),
    )
    featured_image = models.FileField(upload_to="Media/featured_img",null=True)
    featured_video = models.CharField(max_length=300,null=True)
    title = models.CharField(max_length=500)
    course_type = models.CharField(choices=COURSE_TYPE,max_length=4, default='FREE')
    created_at = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE,null=True)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True)
    language = models.ForeignKey(Language,on_delete=models.CASCADE,null=True)
    deadline = models.CharField(max_length=100,null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    status = models.CharField(choices=STATUS,max_length=100,null=True)
    has_certificate = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("course_details", kwargs={'slug': self.slug})
    
    def instructor_get_absolute_url(self):
        from django.urls import reverse
        return reverse("instructor_course_details", kwargs={'slug': self.slug})

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Course)


USER_ROLE = (
        ('Learner','Learner'),
        ('Instructor', 'Instructor'),
    )
class Role(models.Model):
    role = models.CharField(choices=USER_ROLE, blank=False, max_length=10, null=False)
    
    def __str__(self):
        return self.role

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course_review = models.CharField(max_length=100)
    comment = models.CharField(max_length=1000)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.course_review + " - " + self.comment

class What_you_learn(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points

class Requirements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name + " -  " + self.course.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("lesson_details", kwargs={'slug': self.id})

class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/Yt_Thumbnail",null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    lessson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    description = models.TextField(null=True)
    youtube_id = models.CharField(max_length=200, null=True, blank=True)
    video_file = models.FileField(upload_to='ProtectedVideoLectures', null=True, blank=True)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("video_lecture_details", kwargs={'slug': self.youtube_id})

# class PUBLIC_VIDEO(Video):
#         youtube_id = models.CharField(max_length=200, null=True)
#
#         def get_absolute_url(self):
#             from django.urls import reverse
#             return reverse("video_lecture_details", kwargs={'slug': self.youtube_id})

# class PROTECTED_VIDEO(Video):
#         video_file = models.FileField(upload_to='/ProtectedVideoLectures')

class UserCourse(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title


    
class UserRole(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    role = models.ForeignKey(Role,on_delete=models.CASCADE)

    print(role)

    def __str__(self):
        return self.user.username + " - " + self.role.role


class Payment(models.Model):
    order_id = models.CharField(max_length=100,null=True,blank=True)
    user_course = models.ForeignKey(UserCourse,on_delete=models.CASCADE,null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,null=True)
    country = models.CharField(max_length=100, default="")
    address_1 = models.CharField(max_length=255, default="")
    address_2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, default="")
    state = models.CharField(max_length=100, default="")
    postcode = models.CharField(max_length=20, default="")
    phone = models.CharField(max_length=20, default="")
    email = models.EmailField(max_length=100, default="")
    order_comments = models.TextField(blank=True)
    total = models.IntegerField(null=False, default=0)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name + " -- " + self.course.title

difficulties = (
    ('Easy','Easy'),
    ('Medium','Medium'),
    ('Hard','Hard'),
)
class Quizzes(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE, null=True)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    topic = models.CharField(max_length=100)
    number_of_questions = models.IntegerField(null=True)
    time_duration = models.IntegerField(null=True)
    require_passing_score = models.IntegerField(null=True)
    status = models.BooleanField(default=False)
    total_attempts = models.IntegerField(null=True)
    difficulty_level = models.CharField(choices=difficulties,max_length=100,null=True)

    def __str__(self):
        return self.topic + " - " + self.course.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("quiz_details", kwargs={'slug': self.slug})
    
    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]


def create_slug_quizzes(instance, new_slug=None):
    slug = slugify(instance.topic)
    if new_slug is not None:
        slug = new_slug
    qs = Quizzes.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug_quizzes(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver_quizzes(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug_quizzes(instance)

pre_save.connect(pre_save_post_receiver_quizzes, Quizzes)

class Question(models.Model):
    text = models.CharField(max_length=1000)
    quizzes = models.ForeignKey(Quizzes,on_delete=models.CASCADE)
    point = models.IntegerField(default=25)
    status = models.BooleanField(default=False)
    def __str__(self):
        return self.text
    
    def get_answers(self):
        return self.answer_set.all()

    def get_question_with_answers(self):
        answers = self.get_answers()
        question_info = {
            "question_text": self.text,
            "point": self.point,
            "status": self.status,
            "answers": [
                {"text": answer.text, "correct": answer.correct}
                for answer in answers
            ]
        }
        return question_info

    def get_absolute_url(self):
        from django.urls import reverse

LMS/app/templates/app/instructor/course.html
{% extends 'app/instructor_base.html' %}
{% block title %}Instructor Courses{% endblock %}
{% block content %}

<body>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
     <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
     <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>Instructor · Courses</title>

    <style>

        div.scroll {
            width: 100%;
            height: 500px;
            overflow-x: hidden;
            overflow-y: auto;
          }

       .filter-data {
          margin-top: 8px;
        }

    </style>
  </head>

  <div class="container col-sm">
    <div class="panel panel-primary" style="border-width: 3px; border-radius: 6px; border-color: #052d71;">
      <div class="panel-heading" style="background: linear-gradient( #052d71  , #052d71 );">
        <h6 class="panel-title" style="text-align: center ;font-weight: bold; font-size: 30px; color: #ffffff;">My Courses</h6>
      </div>

      <div class="scroll" style="width: 100%; height: 500px; overflow-x: hidden; overflow-y: auto;">
          <div class="card card-body p-4 mt-7 shadow-dark" style="float: right; margin: 10px 5px;">
              <!-- Search -->

              <form class="w-100 form-inline" method="get" action="{% url 'instructor_search_course'%}">
                <div class="form-group mx-sm-3 mb-2"  style="width: 40%; float: left;">
                  <input type="text" class="form-control" id="search" placeholder="Search bar" name="query">
                </div>
                <button type="submit" class="btn btn-primary mb-2" style="background: linear-gradient( #36d1dc   , #5b86e5 );"><i class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                <div class="filter-data">
                  <span><b>Status</b>:</span>
                  <label class="radio-inline">
                    <input class="form-check-input" type="radio" name="status" id="statusAll" value="All" checked>All
                  </label>
                  <label class="radio-inline">
                    <input  class="form-check-input" type="radio" name="status" id="statusConfirmed" value="Confirmed" >Confirmed
                  </label>
                  <label class="radio-inline">
                    <input class="form-check-input" type="radio" name="status" id="statusPending" value="Pending" >Pending
                  </label>
                </div>
              </form>
            
          </div>

      <table class="table table-hover" id="dev-table">
        <thead>
          <tr style="font-weight: bold; font-size: 16px;">
            <th>Title</th>
            <th>Category</th>
            <th>Level</th>
            <th>Language</th>
            <th>Price</th>
            <th>Certificate</th>
            <th>Leanrers</th>
            <th>Status</th>
          </tr>
        </thead>
        {% for a in courses %}
        <tr>
          <td><a href="{{a.instructor_get_absolute_url}}"><b>{{a.title}}</b></a></td>
          <td>{{a.category}}</td>
          <td>{{a.level}}</td>
          <td>{{a.language}}</td>
          <td>{{a.price}}</td>
          <td>{{a.has_certificate}}</td>
          <td>{{a.usercourse_set.all.count}}</td>
          {%if a.status == 'PUBLISH'%}
          <td><span class="label label-success">Confirmed</span></td>
          {% else %}
          <td><span class="label label-warning">Pending</span></td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
      </div>
    </div>
      <a href="{% url 'create_course_form' %}" class="btn btn-primary" style="background-color: #052d71;">Create new Course <i class="fa-solid fa-plus"></i> </a>
  </div>
 
</body>
{% endblock %}

LMS/app/templates/app/instructor/course_search.html
{% extends 'app/instructor_base.html' %}
{% block title %}Instructor Courses{% endblock %}
{% block content %}

<body>
 
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
     <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
     <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>Instructor · Courses</title>

    <style>
        body{
          background-image: url('../../static/assets/img/illustrations/illustration-7.svg') !important; 
          background-repeat: no-repeat; 
          background-size: cover;
        }
        div.scroll {
            background-color: #ffffff;
            width: 100%;
            height: 500px;
            overflow-x: hidden;
            overflow-y: auto;
          }

       .filter-data {
          margin-top: 8px;
        }
        
    </style>
  </head>

  <div class="container col-sm" >
    <div class="panel panel-primary" style="border-width: 3px; border-radius: 6px; border-color: #052d71;">
      <div class="panel-heading" style="background: linear-gradient( #052d71  , #052d71 );">
        <h6 class="panel-title" style="text-align: center ;font-weight: bold; font-size: 30px; color: #ffffff;">My Courses</h6>
      </div>

      <div class="scroll" style="background-color: #ffffff; width: 100%; height: 500px; overflow-x: hidden; overflow-y: auto;">
          <div class="card card-body p-4 mt-7 shadow-dark" style="float: right; margin: 10px 5px;">
              <!-- Search -->

              <form class="w-100 form-inline" method="get" action="{% url 'instructor_search_course'%}">
                <div class="form-group mx-sm-3 mb-2"  style="width: 40%; float: left;">
                  <input type="text" class="form-control" id="search" placeholder="Search bar" name="query">
                </div>
                <button type="submit" class="btn btn-primary mb-2" style="background: linear-gradient( #36d1dc   , #5b86e5 );"><i class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                <!-- <div class="filter-data form-check form-check-inline">
                  <span><b>Status</b>:</span>
                  <input class="form-check-input" type="radio" name="status" id="status" value="Confirmed">
                  <span class="form-check" for="inlineRadio1">Confirmed</span>
                  <input class="form-check-input" type="radio" name="status" id="status" value="Pending">
                  <span class="form-check" for="inlineRadio2">Pending</span>
                  <input class="form-check-input" type="radio" name="status" id="status" value="All" checked>
                  <span class="form-check" for="inlineRadio2">All</span>
                </div> -->
                <div class="filter-data">
                  <span><b>Status</b>:</span>
                  <label class="radio-inline">
                    <input class="form-check-input" type="radio" name="status" id="status" value="All" checked>All
                  </label>
                  <label class="radio-inline">
                    <input  class="form-check-input" type="radio" name="status" id="status" value="Confirmed" >Confirmed
                  </label>
                  <label class="radio-inline">
                    <input class="form-check-input" type="radio" name="status" id="status" value="Pending" >Pending
                  </label>
                </div>

                <!-- <div class="filter-data">
                  <span><b>Category</b>:</span>
                  <select name="category" class="form-select" aria-label="Default select example">
                    <option value="All">Select category</option>
                    {% for c in categories %}
                      <option value={{c.name}}>{{c.name}}</option>
                    {% endfor %}
                  </select>
                </div> -->
                
                <!-- <div class="filter-data">
                  <span><b>Level</b>:</span>
                  <select name="level" class="form-select" aria-label="Default select example">
                    <option value="All">Select level</option>
                    {% for l in levels %}
                      <option value={{l.name}}>{{l.name}}</option>
                    {% endfor %}
                  </select>
                </div> -->
              </form>
            
          </div>

      <table class="table table-hover" id="dev-table">
        <thead>
          <tr style="font-weight: bold; font-size: 16px;">
            <th>Title</th>
            <th>Category</th>
            <th>Level</th>
            <th>Language</th>
            <th>Price</th>
            <th>Certificate</th>
            <th>Status</th>
          </tr>
        </thead>
        {% for a in courses %}
        <tr>
          <td><a href="{{a.instructor_get_absolute_url}}"><b>{{a.title}}</b></a></td>
          <td>{{a.category}}</td>
          <td>{{a.level}}</td>
          <td>{{a.language}}</td>
          <td>{{a.price}}</td>
          <td>{{a.has_certificate}}</td>
          {%if a.status == 'PUBLISH'%}
          <td><span class="label label-success">Confirmed</span></td>
          {% else %}
          <td><span class="label label-warning">Pending</span></td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
      </div>
    </div>
      <a href="{% url 'create_course_form' %}" class="btn btn-primary" style="background-color: #052d71;">Create new Course <i class="fa-solid fa-plus"></i> </a>
  </div>
 
</body>
{% endblock %}